apiVersion: v1
kind: Service
metadata:
  name: order-service  # Nama unik untuk Service
  labels:
    app: order-service  # Label yang digunakan untuk seleksi objek
spec:
  ports:
  - port: 3000  # Port yang digunakan oleh Layanan
    targetPort: 3000
  selector:
    app: order-service  # Seleksi pod yang akan dilayani oleh layanan ini
  type: NodePort  # Jenis Service, dalam hal ini, NodePort (memungkinkan akses dari luar kluster)
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment  # Nama unik untuk Deployment
  labels:
    app: order-deployment  # Label yang digunakan untuk seleksi objek
spec:
  replicas: 2  # Jumlah replika Pod yang akan dibuat oleh Deployment
  selector:
    matchLabels:
      app: order-deployment  # Seleksi pod yang akan di-manage oleh Deployment
  template:
    metadata:
      labels:
        app: order-deployment  # Label untuk Pod yang akan dibuat oleh Deployment
    spec:
      containers:
      - name: order
        image: ghcr.io/bagusadlan/order-service:latest  # Nama Docker image dari GitHub Container Registry
        ports:
          - containerPort: 3000  # Port yang digunakan oleh kontainer
        env:
          - name: AMQP_URL  # Tambah variabel
            value: "amqp://rabbitmq:5672"